// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Wallpaper = { id: string, is_favorite: boolean, signature: string, path: string, thumbnail_path: string, resolution: string | null, wallpaper_source_id: string, keywords: string | null, };
